[package]
name = "proc-macro-hack"
version = "0.3.3"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Procedural functionlike!() macros using only Macros 1.1"
repository = "https://github.com/dtolnay/proc-macro-hack"

[features]
default = []
proc_macro = []

[dependencies]
proc-macro-hack-impl = { version = "0.3", path = "impl" }

[dev-dependencies]
demo-hack = "0.0.3"
demo-hack-impl = "0.0.3"
